#!/bin/sh
#chkconfig: 345 60 40
   #description:epics web app
start(){
export V=`ps -ef|grep -v grep|grep "SCREEN -dmS epicsWeb"`
if [ $V=="" ];then
echo -n $"Starting $prog:"
screen -dmS epicsWeb
sleep 0.5
echo "epicsWeb app"
screen -S epicsWeb -p 0 -X eval 'stuff "cd /opt/gitHub/RMS_WEB/ \015"'
screen -S epicsWeb -p 0 -X eval 'stuff "pm2 start ./bin/www --name epicsWeb --watch \015"'
echo "epicsWeb Node web is Running";
else
return 0;
fi



}

stop(){
echo -n $"Shutting down $Prog:"
screen -S epicsWeb -p 0 -X eval 'stuff "pm2 delete epicsWeb\015"'
screen -S epicsWeb -p 0 -X eval 'stuff "exit \015"'
echo "epicsWeb is Stoping"
return 0
}
restart() {
        stop
        start
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
restart)
        restart
        ;;
esac